-- ============================================================
-- Ginkoyes V2 — MariaDB Schema
-- 24 tables miroir de Ginkoia (Firebird)
-- Ordre : dépendances FK respectées
-- ============================================================

CREATE DATABASE IF NOT EXISTS ginkoyes
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE ginkoyes;

-- ============================================================
-- Tier 1 : Tables sans FK (référentiels)
-- ============================================================

CREATE TABLE IF NOT EXISTS ARTMARQUE (
  MRK_ID       INT          NOT NULL PRIMARY KEY,
  MRK_NOM      VARCHAR(100) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ARTGENRE (
  GRE_ID       INT          NOT NULL PRIMARY KEY,
  GRE_NOM      VARCHAR(100) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS NKLRAYON (
  RAY_ID       INT          NOT NULL PRIMARY KEY,
  RAY_NOM      VARCHAR(100) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ARTCLASSEMENT (
  CLA_ID       INT          NOT NULL PRIMARY KEY,
  CLA_NOM      VARCHAR(100) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ARTFOURN (
  FOU_ID       INT          NOT NULL PRIMARY KEY,
  FOU_NOM      VARCHAR(200) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PLXTAILLESGF (
  TGF_ID       INT          NOT NULL PRIMARY KEY,
  TGF_NOM      VARCHAR(50)  DEFAULT NULL,
  TGF_CORRES   VARCHAR(50)  DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PLXCOULEUR (
  COU_ID       INT          NOT NULL PRIMARY KEY,
  COU_NOM      VARCHAR(100) DEFAULT NULL,
  COU_CODE     VARCHAR(50)  DEFAULT NULL,
  COU_ARTID    INT          DEFAULT NULL
) ENGINE=InnoDB;

-- ============================================================
-- Tier 2 : Familles / Sous-familles (hiérarchie rayon)
-- ============================================================

CREATE TABLE IF NOT EXISTS NKLFAMILLE (
  FAM_ID       INT          NOT NULL PRIMARY KEY,
  FAM_NOM      VARCHAR(100) DEFAULT NULL,
  FAM_RAYID    INT          DEFAULT NULL,
  CONSTRAINT FK_FAM_RAY FOREIGN KEY (FAM_RAYID) REFERENCES NKLRAYON(RAY_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS NKLSSFAMILLE (
  SSF_ID       INT          NOT NULL PRIMARY KEY,
  SSF_NOM      VARCHAR(100) DEFAULT NULL,
  SSF_FAMID    INT          DEFAULT NULL,
  CONSTRAINT FK_SSF_FAM FOREIGN KEY (SSF_FAMID) REFERENCES NKLFAMILLE(FAM_ID)
) ENGINE=InnoDB;

-- ============================================================
-- Tier 3 : Articles (table centrale)
-- ============================================================

CREATE TABLE IF NOT EXISTS ARTARTICLE (
  ART_ID       INT          NOT NULL PRIMARY KEY,
  ART_NOM      VARCHAR(200) DEFAULT NULL,
  ART_REFMRK   VARCHAR(100) DEFAULT NULL,
  ART_CODE     VARCHAR(50)  DEFAULT NULL,
  ART_CODEFOURN VARCHAR(50) DEFAULT NULL,
  ART_MRKID    INT          DEFAULT NULL,
  ART_GREID    INT          DEFAULT NULL,
  ART_SSFID    INT          DEFAULT NULL,
  CONSTRAINT FK_ART_MRK FOREIGN KEY (ART_MRKID) REFERENCES ARTMARQUE(MRK_ID),
  CONSTRAINT FK_ART_GRE FOREIGN KEY (ART_GREID) REFERENCES ARTGENRE(GRE_ID),
  CONSTRAINT FK_ART_SSF FOREIGN KEY (ART_SSFID) REFERENCES NKLSSFAMILLE(SSF_ID)
) ENGINE=InnoDB;

-- ============================================================
-- Tier 4 : Collections, Tickets, BL
-- ============================================================

CREATE TABLE IF NOT EXISTS ARTCOLLECTION (
  COL_ID       INT          NOT NULL PRIMARY KEY,
  COL_NOM      VARCHAR(200) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CSHTICKET (
  TKE_ID       INT          NOT NULL PRIMARY KEY,
  TKE_DATE     DATE         DEFAULT NULL,
  TKE_NUMERO   VARCHAR(50)  DEFAULT NULL,
  TKE_TOTALTTC DECIMAL(15,2) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS NEGBL (
  BLE_ID       INT          NOT NULL PRIMARY KEY,
  BLE_DATE     DATE         DEFAULT NULL,
  BLE_NUMERO   VARCHAR(50)  DEFAULT NULL,
  BLE_WEB      SMALLINT     DEFAULT 0
) ENGINE=InnoDB;

-- ============================================================
-- Tier 5 : Références, Stock, Commandes, Réceptions
-- ============================================================

CREATE TABLE IF NOT EXISTS ARTREFERENCE (
  ARF_ID       INT          NOT NULL PRIMARY KEY,
  ARF_ARTID    INT          DEFAULT NULL,
  ARF_CHRONO   VARCHAR(50)  DEFAULT NULL,
  ARF_ICLID1   INT          DEFAULT NULL,
  CONSTRAINT FK_ARF_ART FOREIGN KEY (ARF_ARTID) REFERENCES ARTARTICLE(ART_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ARTCOLART (
  CAR_ID       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CAR_ARTID    INT          NOT NULL,
  CAR_COLID    INT          NOT NULL,
  INDEX idx_car_artid_colid (CAR_ARTID, CAR_COLID),
  CONSTRAINT FK_CAR_ART FOREIGN KEY (CAR_ARTID) REFERENCES ARTARTICLE(ART_ID),
  CONSTRAINT FK_CAR_COL FOREIGN KEY (CAR_COLID) REFERENCES ARTCOLLECTION(COL_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS AGRSTOCKCOUR (
  STC_ARTID    INT          NOT NULL,
  STC_TGFID    INT          NOT NULL,
  STC_COUID    INT          NOT NULL,
  STC_QTE      INT          DEFAULT 0,
  STC_PUMP     DECIMAL(15,4) DEFAULT 0,
  PRIMARY KEY (STC_ARTID, STC_TGFID, STC_COUID),
  CONSTRAINT FK_STC_ART FOREIGN KEY (STC_ARTID) REFERENCES ARTARTICLE(ART_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS COMBCDE (
  CDE_ID       INT          NOT NULL PRIMARY KEY,
  CDE_COLID    INT          DEFAULT NULL,
  CDE_FOUID    INT          DEFAULT NULL,
  CDE_DATE     DATE         DEFAULT NULL,
  CONSTRAINT FK_CDE_COL FOREIGN KEY (CDE_COLID) REFERENCES ARTCOLLECTION(COL_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS RECBR (
  BRE_ID       INT          NOT NULL PRIMARY KEY,
  BRE_DATE     DATE         DEFAULT NULL,
  BRE_NUMERO   VARCHAR(50)  DEFAULT NULL,
  BRE_NUMFOURN VARCHAR(50)  DEFAULT NULL,
  BRE_FOUID    INT          DEFAULT NULL,
  BRE_COLID    INT          DEFAULT NULL,
  CONSTRAINT FK_BRE_FOU FOREIGN KEY (BRE_FOUID) REFERENCES ARTFOURN(FOU_ID),
  CONSTRAINT FK_BRE_COL FOREIGN KEY (BRE_COLID) REFERENCES ARTCOLLECTION(COL_ID)
) ENGINE=InnoDB;

-- ============================================================
-- Tier 6 : Tables de lignes (FK vers Tier 4/5)
-- ============================================================

CREATE TABLE IF NOT EXISTS ARTCLAITEM (
  CIT_ID       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CIT_ICLID    INT          DEFAULT NULL,
  CIT_CLAID    INT          DEFAULT NULL,
  INDEX idx_cit_iclid (CIT_ICLID),
  CONSTRAINT FK_CIT_CLA FOREIGN KEY (CIT_CLAID) REFERENCES ARTCLASSEMENT(CLA_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ARTCODEBARRE (
  CBI_ID       INT          NOT NULL PRIMARY KEY,
  CBI_CB       VARCHAR(100) DEFAULT NULL,
  CBI_ARFID    INT          DEFAULT NULL,
  CONSTRAINT FK_CBI_ARF FOREIGN KEY (CBI_ARFID) REFERENCES ARTREFERENCE(ARF_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CSHTICKETL (
  TKL_ID       INT          NOT NULL PRIMARY KEY,
  TKL_TKEID    INT          NOT NULL,
  TKL_ARTID    INT          DEFAULT NULL,
  TKL_NOM      VARCHAR(200) DEFAULT NULL,
  TKL_QTE      INT          DEFAULT 0,
  TKL_PXBRUT   DECIMAL(15,2) DEFAULT 0,
  TKL_REMISE   DECIMAL(15,4) DEFAULT 0,
  TKL_PXNET    DECIMAL(15,2) DEFAULT 0,
  TKL_PXNNHT   DECIMAL(15,2) DEFAULT 0,
  TKL_TGFID    INT          DEFAULT NULL,
  TKL_COUID    INT          DEFAULT NULL,
  CONSTRAINT FK_TKL_TKE FOREIGN KEY (TKL_TKEID) REFERENCES CSHTICKET(TKE_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS NEGBLL (
  BLL_ID       INT          NOT NULL PRIMARY KEY,
  BLL_BLEID    INT          NOT NULL,
  BLL_ARTID    INT          DEFAULT NULL,
  BLL_QTE      INT          DEFAULT 0,
  BLL_PXBRUT   DECIMAL(15,2) DEFAULT 0,
  BLL_PXNET    DECIMAL(15,2) DEFAULT 0,
  BLL_PXNN     DECIMAL(15,2) DEFAULT 0,
  BLL_TGFID    INT          DEFAULT NULL,
  BLL_COUID    INT          DEFAULT NULL,
  CONSTRAINT FK_BLL_BLE FOREIGN KEY (BLL_BLEID) REFERENCES NEGBL(BLE_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS COMBCDEL (
  CDL_ID       INT          NOT NULL PRIMARY KEY,
  CDL_CDEID    INT          NOT NULL,
  CDL_ARTID    INT          DEFAULT NULL,
  CDL_COUID    INT          DEFAULT NULL,
  CDL_TGFID    INT          DEFAULT NULL,
  CDL_QTE      INT          DEFAULT 0,
  CDL_PXACHAT  DECIMAL(15,4) DEFAULT 0,
  CDL_PXVENTE  DECIMAL(15,2) DEFAULT 0,
  CDL_REMISE1  DECIMAL(10,4) DEFAULT 0,
  CDL_REMISE2  DECIMAL(10,4) DEFAULT 0,
  CDL_REMISE3  DECIMAL(10,4) DEFAULT 0,
  CONSTRAINT FK_CDL_CDE FOREIGN KEY (CDL_CDEID) REFERENCES COMBCDE(CDE_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS RECBRL (
  BRL_ID       INT          NOT NULL PRIMARY KEY,
  BRL_BREID    INT          NOT NULL,
  BRL_ARTID    INT          DEFAULT NULL,
  BRL_QTE      INT          DEFAULT 0,
  BRL_PXACHAT  DECIMAL(15,4) DEFAULT 0,
  BRL_PXVENTE  DECIMAL(15,2) DEFAULT 0,
  BRL_TGFID    INT          DEFAULT NULL,
  BRL_COUID    INT          DEFAULT NULL,
  CONSTRAINT FK_BRL_BRE FOREIGN KEY (BRL_BREID) REFERENCES RECBR(BRE_ID)
) ENGINE=InnoDB;
