-- ============================================================
-- Ginkoyes V2 — Tables Atelier extended + colonnes client
-- ============================================================

USE ginkoyes;

-- Colonnes supplementaires CLTCLIENT
ALTER TABLE CLTCLIENT
  ADD COLUMN IF NOT EXISTS CLT_CIVID         INT          DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS CLT_NAISSANCE     DATE         DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS CLT_TYPE          INT          DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS CLT_TELTRAVAIL_FAX VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS CLT_PREMIERPASS   DATETIME     DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS CLT_DERNIERPASS   DATETIME     DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS CLT_OPINSMS       SMALLINT     DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS CLT_OPTINEMAIL    SMALLINT     DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS CLT_ARCHIVE       SMALLINT     DEFAULT NULL;

-- Referentiels atelier
CREATE TABLE IF NOT EXISTS SAVTYPE (
  STY_ID     INT          NOT NULL PRIMARY KEY,
  STY_NOM    VARCHAR(200) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SAVTYPMAT (
  TYM_ID     INT          NOT NULL PRIMARY KEY,
  TYM_NOM    VARCHAR(200) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SAVRAYON (
  SVR_ID      INT          NOT NULL PRIMARY KEY,
  SVR_NOM     VARCHAR(200) DEFAULT NULL,
  SVR_ORDRE   INT          DEFAULT NULL,
  SVR_ENABLED SMALLINT     DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SAVTAUXH (
  TXH_ID     INT            NOT NULL PRIMARY KEY,
  TXH_NOM    VARCHAR(200)   DEFAULT NULL,
  TXH_PRIX   DECIMAL(15,4)  DEFAULT NULL
) ENGINE=InnoDB;

-- Forfaits atelier
CREATE TABLE IF NOT EXISTS SAVFORFAIT (
  FOR_ID     INT            NOT NULL PRIMARY KEY,
  FOR_NOM    VARCHAR(200)   DEFAULT NULL,
  FOR_PRIX   DECIMAL(15,4)  DEFAULT NULL,
  FOR_DUREE  DECIMAL(10,2)  DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SAVFORFAITL (
  FOL_ID     INT            NOT NULL PRIMARY KEY,
  FOL_ARTID  INT            DEFAULT NULL,
  FOL_TGFID  INT            DEFAULT NULL,
  FOL_COUID  INT            DEFAULT NULL,
  FOL_QTE    DECIMAL(15,4)  DEFAULT NULL,
  FOL_FORID  INT            DEFAULT NULL
) ENGINE=InnoDB;

-- Detail materiel
CREATE TABLE IF NOT EXISTS SAVMATDETAIL (
  MAD_ID          INT          NOT NULL PRIMARY KEY,
  MAD_MATID       INT          DEFAULT NULL,
  MAD_DESIGNATION VARCHAR(200) DEFAULT NULL,
  MAD_VALUE       VARCHAR(200) DEFAULT NULL,
  MAD_COMMENT     TEXT         DEFAULT NULL,
  MAD_NUMBER      VARCHAR(100) DEFAULT NULL,
  MAD_BUYDATE     DATE         DEFAULT NULL,
  MAD_WARRANTLY   DATE         DEFAULT NULL,
  MAD_HS          SMALLINT     DEFAULT NULL
) ENGINE=InnoDB;

-- Historique fiches atelier
CREATE TABLE IF NOT EXISTS SAVHISTO (
  SAH_ID          INT          NOT NULL PRIMARY KEY,
  SAH_SAVID       INT          DEFAULT NULL,
  SAH_EVENT       VARCHAR(200) DEFAULT NULL,
  SAH_DATE        DATETIME     DEFAULT NULL,
  SAH_VALUEBEFORE TEXT         DEFAULT NULL,
  SAH_VALUEAFTER  TEXT         DEFAULT NULL,
  SAH_USER        VARCHAR(100) DEFAULT NULL
) ENGINE=InnoDB;

-- Liaison fiche / points de controle
CREATE TABLE IF NOT EXISTS SAVFICHEPC (
  SPC_ID     INT NOT NULL PRIMARY KEY,
  SPC_PCEID  INT DEFAULT NULL,
  SPC_PCLID  INT DEFAULT NULL,
  SPC_SAVID  INT DEFAULT NULL
) ENGINE=InnoDB;
